meteread:
  image: ghcr.io/meteread-lib/meteread
  tag: main
  updateStrategy: RollingUpdate
  command:
    - read
    - electricity_and_gas
  serialDevice: /dev/ttyUSB0

influxdb:
  image: arm64v8/influxdb
  tag: 3-core
  updateStrategy: RollingUpdate
  dataStorage: 5Gi
  pluginsStorage: 1Gi
  service:
    port: 8181
