meteread:
  image: ghcr.io/meteread-lib/meteread
  tag: main
  command:
    - read
    - electricity_and_gas
  serialDevice: /dev/ttyUSB0

influxdb:
  image: ghcr.io/refluxdb/refluxdb
  tag: latest
  dataStorage: 10Gi
  pluginsStorage: 1Gi
  service:
    port: 8181
