apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "meteread.fullname" . }}-influxdb-data
  labels:
    {{- include "meteread.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.influxdb.dataStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "meteread.fullname" . }}-influxdb-plugins
  labels:
    {{- include "meteread.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.influxdb.pluginsStorage }}
